
from __future__ import annotations

import re
import h5py
import pandas as pd
import numpy as np
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import threading
from typing import Any
from collections.abc import Callable

from testsuit.misc.logger import get_logger
from testsuit.misc.MonitorProgress import MonitorProgress

from testsuit.datatools.DataFileMgrs.AFileMgr import AFileMgr


H5_MAX_NB_WORKERS=16

def GetH5FileType(fileName: str, h5File: h5py.File | None=None) -> str:
    if not h5File:
        h5File=h5py.File(fileName, 'r')

    # Dewesoft files
    if "File name" in h5File.attrs and \
        (h5File.attrs["File name"].lower().endswith("dxd") or h5File.attrs["File name"].lower().endswith("d7d")):
        return "Dewesoft"

    # Files generated by Channels tools
    for name, h5obj in h5File.items():
        if isinstance(h5obj,h5py.Group) and name=="channels":
            return "channels" 
            
    # Files generated by functional simulation
    for name, h5obj in h5File.items():
        if isinstance(h5obj,h5py.Group) and "LOG_SENS" in h5obj:
            return "FES"     
       
    return "Generic"

class H5FileMgr(AFileMgr):
    def __init__(self,filename: str,fileIdx: int=0) -> None:
        super().__init__(filename,fileIdx)
        self.__h5Root=h5py.File(self.getFileName(), 'r')
        self.__selectedH5Fields={}
        self.__tables=[]
    
    def getH5FileType(self) -> str:
        return GetH5FileType(self.getFileName(),self.getH5FileRoot())
 
    def getH5FileRoot(self) -> h5py.File:
        return self.__h5Root
    
    def getFileType(self) -> str:
        return "h5"
    
    # not much sense for a H5 file (may be different values depending on chosen param)
    def getNbEntries(self) -> None:
        return None
    
    def _has_external_storage(self,ds: h5py.Dataset) -> bool:
        """detect if external storage is used -> no multithread access possible then 
        in current version of h5py lib"""
        try:
            nbExternalFiles = len(ds.id.get_create_plist().get_external())
            return nbExternalFiles > 0
        except Exception as e:
            return False
        
    def dumpTreeHtml(self,key: str | None=None,item: h5py.Group | h5py.Dataset | None=None,depth: int=0) -> str:

        if item is None:
            item=self.getH5FileRoot()
            key=self.getBaseName()

        htmlText="<ul>"      

        if type(item) == h5py._hl.group.Group or type(item) == h5py._hl.files.File:
            htmlText+="<li><span style='font-weight:bold;color:blue'>"+key+"</span>"
            if key.startswith("_"):
                htmlText+="<ul><li><span style='color:grey;font-style:italic'>[...] (truncated)</span></li></ul>"
            else:
                for subkey, childItem in item.items():
                    htmlText+=H5FileMgr.dumpTreeHtml(self,subkey,childItem,depth+1)                
                htmlText+="</li>"
        elif type(item) == h5py._hl.dataset.Dataset and item.dtype.kind == 'V': # Compound type
            htmlText+="<li><span style='font-weight:bold;color:green'>"+key+"</span><ul>"
            for colName in item.dtype.fields.keys():
                htmlText+="<li>"+colName+"</li>"
            htmlText+="</ul></li>"
        else:
            htmlText+="<li>"+key+"</li>"

        htmlText+="</ul>"

        return htmlText

    def dumpTreeTxt(self,key: str | None=None,
                    item: h5py.Group | h5py.Dataset | None=None,
                    depth: int=0,
                    indent_text: str="   ") -> str:

        if item is None:
            item=self.getH5FileRoot()
            key=self.getBaseName()

        strText=(indent_text * depth)

        if type(item) == h5py._hl.group.Group or type(item) == h5py._hl.files.File:
            strText+=" @"+key+" "
            if key.startswith("_"):
                strText+="[...] (truncated)\n"
            else:
                strText+="\n"
                for subkey, childItem in item.items():
                    strText+=H5FileMgr.dumpTreeTxt(self,subkey,childItem,depth+1)                
                
        elif type(item) == h5py._hl.dataset.Dataset and item.dtype.kind == 'V': # Compound type
            strText+=" - "+key+" "
            for colName in item.dtype.fields.keys():
                strText+="\n"+(indent_text * (depth+1))+" - "+colName
            strText+="\n"

        else:
            strText+=" * "+key+"\n"

        strText+="\n"

        return strText

    def dumpParamsTxt(self,
                      key: str | None=None,
                      item: h5py.Group | h5py.Dataset | None=None,
                      depth: int=0,path: str="") -> str:

        if item is None:
            item=self.getH5FileRoot()
            key=""
        if key.startswith("/"):
            key=key.removeprefix("/")

        strText=""
        if type(item) == h5py._hl.group.Group or type(item) == h5py._hl.files.File:
            if not key.startswith("_"):                
                for subkey, childItem in item.items():
                    strText+=H5FileMgr.dumpParamsTxt(self,subkey,childItem,path=path+"/"+key)                
                
        elif type(item) == h5py._hl.dataset.Dataset and item.dtype.kind == 'V': # Compound type
            if len(item.dtype.fields)>0:
                for colName in item.dtype.fields.keys():
                    strText+=path+"/"+key+"."+colName+"\n"            
            else:
                strText+=path+"/"+key+"\n"
                
        else:
            strText+=path+"/"+key+"\n"

        return strText

    def toHtmlTbl(self) -> str:
        htmlTbl = "<tr><th>"+"Nb Fields"+"</th><td>"+str(len(self.getFieldNames()))+"</td></tr>"
        htmlTbl += "<tr><th>"+"Type"+"</th><td>"+str(self.getH5FileType())+"</td></tr>"
        return htmlTbl

    def getFieldNames(self) -> list:
        if self._fieldNamesList is None:
            self._fieldNamesList=[]
            def visitorCb(name,item):
                if "/Timestamps/" in name: return
                
                if type(item)==h5py._hl.dataset.Dataset:
                    # for compound types, add table columns names
                    if item.dtype.kind=="V": 
                        self.__tables.append(item)
                        for key in item.dtype.fields.keys():                            
                            self._fieldNamesList.append(name+"."+key)
                    else:
                        self._fieldNamesList.append(name)
                        # display multi-dimensional data with additional index as suffix to param name                        
                        #if len(item.shape)==2 and item.shape[0]>1 and item.shape[1]>1:
                        #    dataDimIdx=0
                        #    if item.shape[1]<item.shape[0]:
                        #        dataDimIdx=1
                        #    for idx in range(1,(item.shape[dataDimIdx])+1):
                        #        self._fieldNamesList.append(name+"."+str(idx))

            self.getH5FileRoot().visititems(visitorCb)

        return self._fieldNamesList

    def getGroupNames(self, val: object=None) -> None:
        pass
        
    # prepare / adapt header (col names mainly) to keep it comatible with main 3rd party tools
    def prepareFile(self,monitorProgress: MonitorProgress) -> None:
       return None
    
    def finalizeH5Dataframe(self,df: pd.DataFrame) -> pd.DataFrame:
        return df

    def getDataset(self,dataset_path: str,index_path: str | None=None) -> tuple[Any, h5py.Dataset | None]:
        """extract required Dataset from our H5 file"""

        dataset_colname=None
        rst=re.match(r"([^.]+)\.([^.]+)",dataset_path)
        if rst:
            dataset_path=rst.group(1)
            dataset_colname=rst.group(2)

        if dataset_path not in self.getH5FileRoot():
            raise ValueError("invalid path:'"+dataset_path+"'")            
        
        try:
            item = self.getH5FileRoot()[dataset_path]
            if not isinstance(item, h5py.Dataset):
                raise ValueError("provided path is not a dataset:'"+dataset_path+"'")                
            value = None
            
            # Check the type and shape of a dataset
            if item.dtype.kind == 'S':  # Fixed-length bytes
                data = item[()]
                if item.size == 1:  # Single string or byte
                    if isinstance(data, bytes):
                        value = data.decode('utf-8')
                    elif isinstance(data.flat[0], bytes):
                        value = data.flat[0].decode('utf-8')
                else:
                    value = [d.decode('utf-8') for d in data.flat]
            elif item.dtype.kind == 'U':  # Fixed-length Unicode
                data = item[()]
                if item.size == 1:  # Single string
                    value = data
                else:
                    value = [str(d) for d in data.flat]
            elif h5py.check_dtype(vlen=item.dtype) in [str, bytes]:
                data = item[()]
                if isinstance(data, (str, bytes)):
                    value = data if isinstance(data, str)\
                        else data.decode('utf-8')
                else:
                    value = [d if isinstance(d, str) else d.decode('utf-8') for d in data.flat]
                    
            elif item.dtype.kind in ['i', 'f', 'u']:
                if item.shape == () or item.size == 1:
                    value = item[()]
                else:
                   value = item
            elif item.dtype.kind == 'b':  # Boolean type
                if item.shape == () or item.size == 1:
                    value = int(item[()].item())
                else:
                    value = item
            elif item.dtype.kind == 'V': # Compound type
                if dataset_colname is None:
                    raise ValueError("provided path is a HDF5 compound dataset, "
                                     +"need a column name as a suffix to provided dataset path: '"+dataset_path+".<my_col>'")
                  
                if dataset_colname not in item.dtype.fields:
                    raise ValueError("column '"+dataset_colname+"' not found in compound dataset '"+dataset_path
                                     +"', available: "+str(list(item.dtype.fields.keys())))
                value=item[dataset_colname]
            # try to retrieve index dataset
            indexDataset=None

            # explicit index path
            if index_path is not None:
                indexDataset=self.getH5FileRoot()[index_path]
                if not isinstance(indexDataset, h5py.Dataset):
                    raise ValueError("provided index path is not a DataSet:'"+indexDataset+"'")
                return value, indexDataset

    # Now we retrieve implicite index DataSet from attributes
            # via an attribute supposed to point to corresponding DataSet
            refAttrs={}

    # 1. try in priority keys of type *ObjRef*
            # retrieve all attributes of type 'Obj Ref'
            for (attrkey,attrVal) in item.attrs.items():
                if type(attrVal)==h5py.ref_dtype:
                    refAttrs[attrkey]=attrVal

            # try to take best one for implicit index (timestamp)
            for (attrkey,attrval) in refAttrs.items():                

                # if only one ref, we use it
                if len(refAttrs.keys())==1:
                    try:
                        indexDataset=self.getH5FileRoot()[attrval]
                    except Exception as e:
                        if "time" in attrkey.lower() or "date" in attrkey.lower():
                            raise ValueError("unable to find reference pointed by attribute '"+str(attrkey)
                                         +"' for param '"+dataset_path+"' in file '"+self.getFileName()+"': "+str(e))       
                            break
                        get_logger().warn("unable to find reference pointed by attribute '"+str(attrkey)
                                     +"' for param '"+dataset_path+"' in file '"+self.getFileName()+"': "+str(e))

                # otherwise use the first with 'time' or 'date' in attribute
                if "time" in attrkey.lower() or "date" in attrkey.lower():
                    indexDataset=self.getH5FileRoot()[attrval]                  

    # 2. if no luck, try to find a *str* attribute with 'time' or 'date' in their name
            if indexDataset is None:
                for (attrkey,attrval) in item.attrs.items():
                    if "time" in attrkey.lower() or "date" in attrkey.lower():
                        try:
                            indexDataset=self.getH5FileRoot()[attrval]
                        except Exception as e:
                            raise ValueError("unable to find reference pointed by attribute '"
                                             +str(attrkey)+"="+str(attrval)+"' for param '"+dataset_path+"' in file '"+self.getFileName()+"': "+str(e))
                                   
                        break

            return value, indexDataset
        
        except Exception as error:
           raise Exception("while extracting HDF5 data: "+str(error))    

    # name df columns after parameter extracted
    def finalizeH5Dataframe(self,
                        paramName: str,
                        dfParam: pd.DataFrame,
                        h5ParamDataset: h5py.Dataset,
                        monitorProgress: MonitorProgress | None = None) -> pd.DataFrame:

        if len(dfParam.columns)==1:
            dfParam.rename(columns={0:paramName},inplace=True)

        # suppose that 3D dataframes are XYZ
        elif len(dfParam.columns)==3:
            dfParam.rename(columns={0:paramName+"_x",1:paramName+"_y",2:paramName+"_z"},inplace=True)

        else:
            cols={}
            for i in range(len(dfParam.columns)):
                cols[i]=paramName+"_"+str(i)
            dfParam.rename(columns=cols,inplace=True)
            
        # Ensure index is float64 for consistent numeric handling
        if dfParam.index.dtype.kind != 'f':  # 'f' indicates floating point
            dfParam.index = dfParam.index.astype('float64')

        dfParam.name=paramName

        return dfParam

    def _loadSingleParam(self,
                     paramPos: int,
                     paramName: str,
                     indexName: str | None,
                     monitorProgress: MonitorProgress,
                     abortEvent: threading.Event | None,
                     minDateSec: float | None,
                     maxDateSec: float | None,
                     callback: Callable | None,
                     shiftDateSec: float | None,
                     shiftDateRegex: str | None,
                     shiftDateInverted: bool | None,
                     silent: bool) -> pd.DataFrame | None:
        """Load a single parameter. Called from a worker thread."""

        monitCurParam = monitorProgress.child(paramName, 1)

        if abortEvent and abortEvent.is_set():
            raise Exception("Received abort event, HDF5 params extraction interrupted")

        logMsg = [f"extracting {paramName}", f"source file: {self.getBaseName()}",
                  f"source type: {self.getFileType()}"]
        (not silent) and monitCurParam.msg(msg=logMsg)

        # skip param if it is its own index
        if indexName == paramName:
            monitCurParam.complete_n(1)
            return None

        try:
            h5ParamDataset, h5IndexDataset = self.getDataset(paramName, indexName)
        except ValueError as e:
            get_logger().error("Could not load any DataSet at path '" + paramName + "' in file '" + self.getFileName() + "' : " + str(e))
            return None

        if h5ParamDataset is None:
            get_logger().error("No DataSet found at path '" + paramName + "' in file '" + self.getFileName() + "'")
            return None
        
        if self._has_external_storage(h5ParamDataset):
            arr = h5ParamDataset[()]
        else:
            arr = np.array(h5ParamDataset)
        
        if arr.shape == ():
            arr = arr.reshape(1, 1)
        elif len(arr.shape) == 1:
            arr = arr.reshape(-1, 1)
        dfParam = pd.DataFrame(arr)

        # Detect HDF5 enum type and populate _enum_mapping
        if isinstance(h5ParamDataset, h5py.Dataset):
            if h5py.check_dtype(enum=h5ParamDataset.dtype):
                enum_type = h5ParamDataset.id.get_type()
                enum_mapping = {}
                for i in range(enum_type.nmembers()):
                    val, name = enum_type.enum(i)
                    enum_mapping[val] = name.decode('utf-8')
                dfParam.enum_mapping = enum_mapping

        # if an index has been identified, assign it as Dataframe index
        indexArray = None
        if h5IndexDataset is not None:
            indexArray = np.array(h5IndexDataset)

            # if data is set horizontally rather than vertically, we fix it here
            if len(indexArray.shape) == 2 and indexArray.shape[0] == 1:
                dfParam = dfParam.transpose()

            elif len(indexArray.shape) > 2:
                raise ValueError("Invalid shape " + str(indexArray.shape) + " for an index " + self.getFileName() + "::" + h5IndexDataset.name
                                + " for param " + h5ParamDataset.name + " " + str(h5ParamDataset.shape))

            # removing empty useless dimensions (size 1)
            indexArray = indexArray.squeeze()

        # removing empty useless dimensions (size 1)
        if len(dfParam.shape) == 2 and dfParam.shape[1] == 1:
            dfParam = dfParam.squeeze()

        if not isinstance(dfParam, pd.DataFrame):
            if isinstance(dfParam, pd.Series):
                dfParam = dfParam.to_frame()
            else:
                dfParam = pd.DataFrame([dfParam])

        # Safely handle scalars, 0-d numpy arrays, or lists
        if indexArray is not None:
            indexArray = np.atleast_1d(indexArray)
            dfParam.index = indexArray
            dfParam.index.name = str(h5IndexDataset.name)
        else:
            dfParam.index.name = "Timestamp"

        dfParam = self.finalizeH5Dataframe(paramName, dfParam, h5ParamDataset, monitCurParam)

        result = self.finalizeParam(dfParam,
                                    name=paramName,
                                    indexName=dfParam.index.name,
                                    columns=dfParam.columns,
                                    origin=self.getFileName(),
                                    minDateSec=minDateSec, maxDateSec=maxDateSec,
                                    shiftDateSec=shiftDateSec, shiftDateRegex=shiftDateRegex, shiftDateInverted=shiftDateInverted,
                                    silent=silent, callback=callback, monitorProgress=monitCurParam.child("finalize"))

        
        return result
    
    def loadParams(self,
               paramNamesList: list[str],
               indexNamesList: list[str] | None = None,
               monitorProgress: MonitorProgress | None = None,
               abortEvent: threading.Event | None = None,
               minDateSec: float | None = None,
               maxDateSec: float | None = None,
               callback: Callable | None = None,
               shiftDateSec: float | None = None,
               shiftDateRegex: str | None = None,
               shiftDateInverted: bool | None = None,
               silent: bool = False) -> list[pd.DataFrame | None]:
        """See parent class AFileMgr for complete description"""

        # need to handle such case for simple H5 file use where no MonitorProgress is needed
        if not monitorProgress:
            monitorProgress = MonitorProgress(name="H5LoadParam")

        monitorProgress.set_total_items(len(paramNamesList))

        # Build list of (paramPos, paramName, indexName) tuples
        tasks = []
        for paramPos, paramName in enumerate(paramNamesList):
            indexName = None
            if indexNamesList is not None and len(indexNamesList) > 0:
                indexName = indexNamesList[paramPos]
            tasks.append((paramPos, paramName, indexName))

        # Filter out tasks where indexName == paramName (they are skipped)
        active_tasks = [(pp, pn, ix) for pp, pn, ix in tasks if ix != pn]

        # Mark skipped params as complete immediately
        for _, pn, ix in tasks:
            if ix == pn:
                monitCurParam = monitorProgress.child(pn, 1)
                monitCurParam.complete_n(1)

        paramsAsDataframes = [None] * len(paramNamesList)

        if not active_tasks:
            return paramsAsDataframes

        # Run parameter loading in parallel
        with ThreadPoolExecutor(max_workers=H5_MAX_NB_WORKERS) as executor:
            future_to_pos = {}
            for paramPos, paramName, indexName in active_tasks:
                future = executor.submit(
                    self._loadSingleParam,
                    paramPos, paramName, indexName,
                    monitorProgress, abortEvent,
                    minDateSec, maxDateSec, callback,
                    shiftDateSec, shiftDateRegex, shiftDateInverted,
                    silent
                )
                future_to_pos[future] = paramPos

            for future in as_completed(future_to_pos):
                paramPos = future_to_pos[future]
                try:
                    result = future.result()
                    if result is not None:
                        paramsAsDataframes[paramPos] = result
                except Exception as exc:
                    get_logger().error(f"Parameter loading failed: {exc}")
                    raise

        return paramsAsDataframes

class H5FileMgrChannels(H5FileMgr):

    def finalizeH5Dataframe(self,
                        paramName: str,
                        dfParam: pd.DataFrame,
                        h5ParamDataset: h5py.Dataset,
                        monitorProgress: MonitorProgress | None = None) -> pd.DataFrame:
        """convert dates from microseconds to seconds"""
        dfParam=super().finalizeH5Dataframe(paramName,dfParam,h5ParamDataset,monitorProgress)
        dfParam.index=dfParam.index/1e6
        return dfParam

class H5FileMgrDewesoft(H5FileMgr):

    def __init__(self,
             filename: str,
             fileIdx: int = 0) -> None:
        super().__init__(filename,fileIdx)
        startDateStr=self.getH5FileRoot().attrs["Start store time"].strip()
        get_logger().debug("H5 Dewesoft File - "+startDateStr+" - "+self.getBaseName())
        
    def getFileInfo(self):
        fileInfo=super().getFileInfo()

        return fileInfo+["H5-Type: Dewesoft",
                    "Sample rate:"+str(self.getH5FileRoot().attrs["Sample rate"])+" Hz",
                    "Start:"+str(self.getH5FileRoot().attrs["Start store time"].strip()),
                    "End:"+str(self.getH5FileRoot().attrs["End store time"].strip())]
    
    def finalizeH5Dataframe(self,
                        paramName: str,
                        dfParam: pd.DataFrame,
                        h5ParamDataset: h5py.Dataset,
                        monitorProgress: MonitorProgress | None = None) -> pd.DataFrame:
                        
        columnsDesc=h5ParamDataset.attrs["Column Description"]
        pattern = re.compile(r'Column \d+:\s+(\S+)')
        colNames=pattern.findall(columnsDesc)
        colsNames={}
        colIdx=0
        timeColIdx=None
        for colName in colNames:
            if colName=="Data":
                colName=paramName
            if colName=="Time":
                timeColIdx=colIdx
            
            colsNames[colIdx]=colName
            colIdx+=1        
        
        # asynchronous data (has a "Time" column)
        # or brute force dataframe with time column but wrong header info ... (yes it happened)
        if timeColIdx is not None \
            or len(h5ParamDataset.shape)==2 and h5ParamDataset.shape[1]==2 and len(colNames)==1:
            dfParam.set_index(dfParam.columns[0],inplace=True)
            dfParam.index.name="Time"
            dfParam.index=dfParam.index.astype('float64') # float64 needed for sufficient precision 
        else:
            acquisitionRate=float(h5ParamDataset.attrs["Acquisition Rate"])
            periodSec=1.0/acquisitionRate
            dfParam.index=pd.Index(np.arange(0,dfParam.index.size*periodSec,periodSec,dtype="float64"))
            dfParam.index.name="Time"

        # offset timestamps if dates are relatives (file shall be exported with relative timestamps)
        # /!\ timestamps are based on "Start store time", not "Start time"
        startDateStr=self.getH5FileRoot().attrs["Start store time"].strip()
        startDate=datetime.strptime(startDateStr, '%d/%m/%Y %H:%M:%S').replace(tzinfo=timezone.utc)
        dfParam.index+=startDate.timestamp()
        
        dfParam.name=paramName
        dfParam.rename(columns={dfParam.columns[0]:paramName},inplace=True)  
        
        return dfParam
        
class H5FileMgrFES(H5FileMgr):

    def __init__(self,
             filename: str,
             fileIdx: int = 0) -> None:
        super().__init__(filename,fileIdx)
        get_logger().debug("H5 FES File - "+self.getBaseName())
        
    def finalizeH5Dataframe(self,
                        paramName: str,
                        dfParam: pd.DataFrame,
                        h5ParamDataset: h5py.Dataset,
                        monitorProgress: MonitorProgress | None = None) -> pd.DataFrame:

        if len(dfParam.columns)==1:
            dfParam.rename(columns={0:paramName},inplace=True)

        # suppose that 3D dataframes are XYZ
        elif len(dfParam.columns)==3:
            if paramName.endswith("inLLA"):
                dfParam.rename(columns={0:paramName+"_latitude",1:paramName+"_longitude",2:paramName+"_altitude"},inplace=True)
            else:
                dfParam.rename(columns={0:paramName+"_x",1:paramName+"_y",2:paramName+"_z"},inplace=True)

        else:
            cols={}
            for i in range(len(dfParam.columns)):
                cols[i]=paramName+"_"+str(i)
            dfParam.rename(columns=cols,inplace=True)

        dfParam.name=paramName

        return dfParam
        