
### handler MDF files as generated by Gantner systems

import threading
from concurrent.futures import ThreadPoolExecutor,wait
from typing import Any
from collections.abc import Callable

import numpy as np 
import pandas as pd

from testsuit.misc.logger import get_logger
from testsuit.misc.MonitorProgress import MonitorProgress
from testsuit.datatools.DataFileMgrs.AFileMgr import AFileMgr

NB_MAX_WORKERS=6

class MdfFileMgr(AFileMgr):
    def __init__(self, filename: str, fileIdx: int) -> None:
        
        super().__init__(filename,fileIdx)
        
        from asammdf import MDF
        self.__mdfile=MDF(filename)

    def getFileType(self) -> str:
        return "mdf"
    
    def getNbEntries(self) -> int:
        if self._nbEntries is None:
            maxSize=0
            for signal in self.__mdfile.iter_channels():
                if maxSize<signal.samples.size:
                    maxSize=signal.samples.size            
            self._nbEntries = maxSize
            
        return self._nbEntries

    def toHtmlTbl(self) -> str:
        htmlTbl=super().toHtmlTbl()
        htmlTbl += "<tr><th>"+"Date Origin (from file name)"+"</th><td>'"+self.__mdfile.start_time.isoformat()+"'</td></tr>"
        
        return htmlTbl

    def getFieldNames(self) -> list[str]:
        if self._fieldNamesList is None:
            self._fieldNamesList=[]
            for signal in self.__mdfile.iter_channels():     
                self._fieldNamesList.append(signal.name)
                    
        return self._fieldNamesList

    # prepare / adapt header (col names mainly) to keep it comatible with main 3rd party tools
    def prepareFile(self, monitorProgress: MonitorProgress) -> None:
        # nothing to do for this format
        return None

    def validateChannel(self, paramName: str, df: pd.DataFrame) -> list[str]:
        """Validate a single MDF channel using asammdf raw/converted sample data.

        Returns a list of issue strings. Empty list means the channel looks healthy.
        Catches corruption that may not surface after pandas DataFrame conversion.
        """
        issues = []
        channel = None
        for sig in self.__mdfile.iter_channels(raw=False):
            if sig.name == paramName:
                channel = sig
                break


        if channel is None:
            issues.append(f"[{paramName}] channel not found in MDF")
            return issues

        converted = channel.samples
        n = len(converted)

        if n == 0:
            issues.append(f"[{paramName}] empty channel (0 samples)")
            return issues

        conv_range = np.ptp(converted)
        
        # std vs range on converted values (catches the exact symptom you saw)
        # see issue #30 
        if n > 1 and conv_range > 0:
            stdNumpy = np.std(converted, ddof=1)
            stdPandas = df[paramName].std()

            if abs(stdPandas-stdNumpy) > 1e-6:
                issues.append(
                    f"[{paramName}] Pandas and Numpy std disagree: (stdPandas={stdPandas:.4g} VS stdNumpy={stdNumpy:.4g}) "
                    f"- raw corruption or bad conversion ?"
                )

        return issues
    
    def loadParams(self,
                paramNamesList: list[str],
                indexNamesList: list[str] | None = None,
                monitorProgress: MonitorProgress | None = None,
                abortEvent: threading.Event | None = None,
                minDateSec: float | None = None,
                maxDateSec: float | None = None,
                callback: Callable[..., Any] | None = None,
                shiftDateSec: float | None = None,
                shiftDateRegex: str | None = None,
                shiftDateInverted: bool | None = None,
                silent: bool = False) -> list[pd.DataFrame]:
        
        # retrieve positions of requested params 
        rstDataframes=[]
        extractedParamsLock=threading.Lock()
        totalToRead=len(paramNamesList)
        issues=[]
        
        monitorProgress.set_total_items(len(paramNamesList))
        def loadParamFromMdfWorker(workerData: dict[str, Any]) -> None:
            nonlocal rstDataframes 
            nonlocal issues
                   
            paramName=workerData["paramName"]
            monitorProgress=workerData["monitorProgress"]
            
            if abortEvent and abortEvent.is_set():
                    raise Exception("Received abort event, DXD params extraction interrupted")
               
            logMsg=[ f"extracting {paramName}", f"source file: {self.getBaseName()}",
                     f"source type: {self.getFileType()}"]
            if not silent: monitorProgress.msg(msg=logMsg)

            try:
                dfParam=self.__mdfile.to_dataframe([paramName],time_as_date=True)
                # convert DatetimeIndex to seconds since epoch
                dfParam.index=dfParam.index.view("int64") / 1_000_000_000.0
                
                dfParam=self.finalizeParam(dfParam,
                            name=paramName.replace("/","_"),
                            indexName="Timestamps/timestamp",
                            origin=self.getFileName(),
                            minDateSec=minDateSec,maxDateSec=maxDateSec,
                            shiftDateSec=shiftDateSec,shiftDateRegex=shiftDateRegex,shiftDateInverted=shiftDateInverted,
                            monitorProgress=monitorProgress,
                            silent=silent,callback=callback)
                
                # validate channels at the raw MDF level before DataFrame conversion
                issues+=self.validateChannel(paramName,dfParam)
                for issue in issues:
                    get_logger().error(issue)
                    monitorProgress.msg(msg=[self.getBaseName(), "sanity check", issue],msgSeverity="error")                        
                        
                with extractedParamsLock:
                    rstDataframes.append(dfParam)

            except Exception as e:
                raise Exception(f"unable to load param '{paramName}' from {self.getBaseName()}: "+str(e))


        workersData=[]    
        paramPos=0
        for paramName in paramNamesList:  
            workersData.append({"paramName":paramName,"monitorProgress":monitorProgress.child(f"finalize {paramName}")})
            paramPos+=1  
                
        nbWorkers=NB_MAX_WORKERS
        with ThreadPoolExecutor(max_workers=nbWorkers) as executor:
            futures = [executor.submit(loadParamFromMdfWorker, workerData) for workerData in workersData]
            wait(futures)
            for fut in futures:
                fut.result()
        
        if len(issues)>0:
            raise Exception(f"File {self.getFileName()} appears to be corrupted")
        
        return rstDataframes