#!/bin/bash

# THIS DOCUMENT AND ITS CONTENTS ARE PROPERTY OF ARIANEGROUP.
# IT SHALL NOT BE COMMUNICATED TO ANY THIRD PARTY WITHOUT THE OWNER'S
# WRITTEN CONSENT | ARIANEGROUP SAS - ALL RIGHTS RESERVED.

rm *.0 || true

for file in *.pem; do ln -s "$file" "$(openssl x509 -hash -noout -in $file).0"; done
