
import argparse
from time import sleep
import sys,os,logging
from functools import partial


from testsuit.misc.logger import create_logger
from testsuit.misc.logger import get_logger
from testsuit.misc.MonitorProgress import MonitorProgress,consoleRichProgressCb,consoleSilentProgressCb

from testsuit.datatools.datatoolbox import SUPPORTED_DATAFILE_EXTENSIONS
from testsuit.datatools.datatoolbox import loadDataframeFromFile,getDateParser,timerange
from testsuit.datatools.DataframeToHdf5 import DataframeToHdf5

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

create_logger("data2h5")

## check if the given file is accessible
def isInputReadable(f):
    if not os.access(f,os.R_OK):
        get_logger().error("{0} does not exist or is not reachable".format(f))
        sys.exit(1)

    return f

# override the parsing error message using logger
class HelpParser(argparse.ArgumentParser):
    def error(self, message):
        get_logger().error("Input Arguments Error : "+message)
        sys.exit(1)


def extract_to_hdf5(h5fileName,paramsDfList):

    for df in paramsDfList:
        get_logger().info("extracting params "+str(df.columns)+"")
        DataframeToHdf5(h5fileName,os.path.basename(df.origin),df,comment="",chunk_size=True)

    return True
        
def data2h5(sourceFolderOrFile,paramRegexes,indices=None,targetFile=None,extensions=["." + fileExt for fileExt in SUPPORTED_DATAFILE_EXTENSIONS],
                                        excludeParamsRegex=None, minDate=None, maxDate=None, mergeParams=True,
                                        shiftDateSec=None,shiftDateRegex=None, shiftDateInverted=None,
                                        listOnly=False, silent=False, 
                                        monitorProgress=None):
    """Extract data into H5 file.
    See __main__ args list for parameters list and usage."""    
    
    minDateSec=None
    maxDateSec=None
    if minDate:
        convFunc=getDateParser(minDate)
        minDateSec=convFunc(minDate).timestamp() if convFunc else minDateSec        
    if maxDate:
        convFunc=getDateParser(maxDate)
        maxDateSec=convFunc(maxDate).timestamp() if convFunc else maxDateSec    
        

    def cbPrintName(df):
            print(df.name)
            
    def cbSaveDfAsH5File(df,monitorProgress=None):

        if df is None:
            get_logger().warning(f"skipping H5 writing of None param from {targetFile}")    
            return True
        
        monitorProgress.set_total_items(1)
        monitorProgress.msg("writing H5 data for "+str(df.name)+"")

        h5GroupName=os.path.basename(df.origin)
        if len(h5GroupName)==0:
            h5GroupName=os.path.basename(os.path.dirname(df.origin))
        comment={}
        comment["Comments"]="Generated by data2h5"
        if minDate: comment["Min Date"]=minDate
        if maxDate: comment["Max Date"]=maxDate
        try:
            DataframeToHdf5(targetFile,h5GroupName,df,comment=comment,chunk_size=True)
        except Exception as e:
            monitorProgress.msg(msg=f"while writing file '{targetFile}' for {df.name} : {str(e)}",msgSeverity="error")
            return False

        monitorProgress.msg(msg=f"generated/updated file '{targetFile}' for {df.name}")
        
        monitorProgress.complete_n(1)
        return True

    def cbprintDf(df,name=None,origin=None):
        if df is not None: 
            print(df.pstr())
        return True


    cbToUse = None
    if listOnly:
        cbToUse=cbPrintName
    elif targetFile==None:
        cbToUse=cbprintDf
    else:
        cbToUse=cbSaveDfAsH5File
        
    dfListRst=loadDataframeFromFile(sourceFolderOrFile,paramRegexes,indices,extensions,
                                    minDateSec=minDateSec,maxDateSec=maxDateSec, 
                                    excludeParamsRegex=excludeParamsRegex,mergeParams=mergeParams,
                                    shiftDateSec=shiftDateSec,shiftDateRegex=shiftDateRegex,
                                    shiftDateInverted=shiftDateInverted,
                                    dryRun=False,monitorProgress=monitorProgress,
                                    silent=silent,callback=cbToUse)

    if len(dfListRst)==0:
        return False, dfListRst
    
    return True, dfListRst


## the main function
def main():
    

    parser = HelpParser(description=
    """Extract given parameters into an HDF5 file. 
        If target file is not provided, simply list matching fields found.
        If params list is empty, list all param names found.

    Return 1 if something went wrong, 0 otherwise
    """,
    formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('sourceFolderOrFile', metavar="FolderOrFile", help="source folder or file  where to scan data files",type=isInputReadable)
    parser.add_argument('target', nargs='?',metavar="Target", help="Target of params contents: xxx.h5")
    parser.add_argument('-l','--list',action='store_true', default=False, help="list all params found in given datasources" )
    parser.add_argument('-p','--params',metavar='param1,param2,...', help="list of params (regexes) to extract into and HDF5 file. You can use python regex. Ex: 'param_02,my_.*4$'",default=".*")
    parser.add_argument('--indices',metavar='paramIdx1,paramIdx2,...', help="use provided params as indices, 'auto' for trying to automatically identify one. Ex: 'param_02_timestamp,auto'")
    parser.add_argument('-d',"--debug",action='store_true', default=False, help="Show debug messages")
    parser.add_argument('-s',"--silent",action='store_true', default=False, help="Only show relevant output messages, no progress.")
    parser.add_argument('--extensions',default=SUPPORTED_DATAFILE_EXTENSIONS, help="List files format to use as input")
    parser.add_argument('--minDate', help="Minimal date of data to record in file")
    parser.add_argument('--maxDate', help="Maximal date of data to record in file")
    
    args = parser.parse_args()
    
    if args.debug==True:
        get_logger().setLevel(logging.DEBUG)

    get_logger().debug(args.target)
    
    monitorProgress=MonitorProgress(progressCb=consoleSilentProgressCb if args.silent else consoleRichProgressCb,
                                       name="data2h5")
        
    rst, dfList = data2h5(args.sourceFolderOrFile,args.params,args.indices,args.target,args.extensions,
                                            args.minDate,args.maxDate,listOnly=args.list,silent=args.silent,
                                            monitorProgress=monitorProgress)

    if rst == True:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
